### ISSUE TITLE
tag=release

### ISSUE THREAD

**Issue by andreineculau** [tomas-abrahamsson/tdiff#2]
Would you be so kind to add a tag on bbb54ce20df388f2c7d01e8df30ef471ca98d0fb ? :) Thanks.

**Comment by tomas-abrahamsson** [comment]
:) Done! Tagged as 0.1

**Comment by andreineculau** [comment]
hehe. great!

On Mon, Mar 14, 2016 at 2:42 PM, Tomas Abrahamsson <notifications@github.com

> wrote:
> 
> :) Done! Tagged as 0.1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomas-abrahamsson/tdiff/issues/2#issuecomment-196315206
> .

## 

andreineculau.com http://www.andreineculau.com
