### ISSUE TITLE
Upload to Hex.pm

### ISSUE THREAD

**Issue by eproxus** [tomas-abrahamsson/tdiff#3]
I'm publishing [Unite](https://github.com/eproxus/unite) which depends on tdiff to Hex.pm. It would be very helpful if tdiff also existed on Hex.pm. Would it be possible for you to upload it? Alternatively, I can also fork it and upload it if you approve of that.

**Comment by tomas-abrahamsson** [comment]
I will look into uploading it.

**Comment by eproxus** [comment]
Thanks! Let me know if you need any assistance

**Comment by tomas-abrahamsson** [comment]
tdiff now exists on hex!
