### ISSUE TITLE
diff_binaries does not seem to work as I expected

### ISSUE THREAD

**Issue by joearms** [tomas-abrahamsson/tdiff#5]
Here are a couple of test cases

    t100() ->
        Old = "A cat ate my hat", 
        New = "A dog ate my shoe",
        P = tdiff:diff(Old, New),
        New = tdiff:patch(Old, P),
        yes.

    t101() ->
        Old = <<"A cat ate my hat">>, 
        New = <<"A dog ate my shoe">>,
        P = tdiff:diff_binaries(Old, New),
        New = tdiff:patch(Old, P),
       yes.

This is what happens when I run them
  
       1> test_tdiff:t100().   
      yes
      2> test_tdiff:t101().
      ** exception error: no match of right hand side value ["A dog ate my shoe"]
          in function  test_tdiff:t101/0 (test_tdiff.erl, line 18)

**Comment by tomas-abrahamsson** [comment]
Oh, hi, I think I should implement `patch_binary` for symmetry. And also document the (somewhat surprising) fact that `diff_binaries` first split the binaries to lists of lines.

**Comment by tomas-abrahamsson** [comment]
I pushed updates containing specs and (e)documentation (will close this ticket). For backwards compatibility, I don't want to change the semantics of the `diff_binaries/2,3` even though I agree it violates the principle of least astonishment.
